### PR TITLE
Args & Launch commands

### PR DESCRIPTION
**Pull request by SrMrBurchick**
So I've added ability to parse args and add to parse and execute launch commands

### CODE REVIEW

**Comment by EthanJWright** [comment]
Would you mind adding a touch more to the readme for this, use case & example maybe? Thanks!

**Comment by SrMrBurchick** [comment]
Done

**Comment by EthanJWright** [comment]
Just a heads up still tracking this - I want to make some refactors to cut down on the duplicated code, and I broke my hand so the refactors are a bit more tedious

**Comment by EthanJWright** [comment]
@SrMrBurchick I refactored some elements here because I didn't want to create the pattern of duplicating all of the files. I believe everything functional you added here should be working in main as of #4 

Closing, open an issue if I missed anything!

**Pull request closed without merging**
